/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 1.0
 */
export interface Config {
  /** @nullable */
  name?: string | null;
  maxRooms?: number;
  maxObjects?: number;
  maxRenovations?: number;
  maxFrames?: number;
}

export interface Obj {
  objectId?: string;
  /** @nullable */
  ownerId: string | null;
  videoUploaded?: boolean;
  modelGenerated?: boolean;
  width?: number;
  height?: number;
  length?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  thumbnail?: string | null;
  /** @nullable */
  purchaseLink?: string | null;
  /** @nullable */
  generationDate?: string | null;
  creationDate?: string;
  /** @nullable */
  uploadDate?: string | null;
  modifyDate?: string;
  /** @nullable */
  error?: string | null;
  public?: boolean;
  type?: ObjectTypes;
}

export interface ObjApiGetReturnType {
  totalCount?: number;
  totalPages?: number;
  currentPage?: number;
  pageSize?: number;
  /** @nullable */
  returnedObjects?: Obj[] | null;
}

export interface ObjectApiGetReturnType {
  totalCount?: number;
  totalPages?: number;
  currentPage?: number;
  pageSize?: number;
  /** @nullable */
  returnedObjects?: unknown[] | null;
}

export interface ObjectInRenovation {
  id?: string;
  objectId?: string;
  renovationId?: string;
  x?: number;
  y?: number;
  z?: number;
  rotationX?: number;
  rotationY?: number;
  rotationZ?: number;
  scaleX?: number;
  scaleY?: number;
  scaleZ?: number;
  visible?: boolean;
}

export interface ObjectInRenovationApiGetReturnType {
  totalCount?: number;
  totalPages?: number;
  currentPage?: number;
  pageSize?: number;
  /** @nullable */
  returnedObjects?: ObjectInRenovation[] | null;
}

export interface ObjectPerms {
  objectId?: string;
  /** @nullable */
  userId: string | null;
  renovationOnly?: boolean;
  canEdit?: boolean;
}

export interface ObjectPermsApiGetReturnType {
  totalCount?: number;
  totalPages?: number;
  currentPage?: number;
  pageSize?: number;
  /** @nullable */
  returnedObjects?: ObjectPerms[] | null;
}

export type ObjectTypes = typeof ObjectTypes[keyof typeof ObjectTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ObjectTypes = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;

export type PortalTypes = typeof PortalTypes[keyof typeof PortalTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PortalTypes = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;

export interface PostObject {
  videoUploaded?: boolean;
  modelGenerated?: boolean;
  public?: boolean;
  width?: number;
  height?: number;
  length?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  thumbnail?: string | null;
  /** @nullable */
  purchaseLink?: string | null;
  type?: ObjectTypes;
}

export interface PostObjectInRenovation {
  objectId?: string;
  renovationId?: string;
  x?: number;
  y?: number;
  z?: number;
  rotationX?: number;
  rotationY?: number;
  rotationZ?: number;
  scaleX?: number;
  scaleY?: number;
  scaleZ?: number;
  visible?: boolean;
}

export interface PostObjectPermissions {
  objectId?: string;
  /** @nullable */
  userId: string | null;
  renovationOnly?: boolean;
  canEdit?: boolean;
}

export interface PostRenovation {
  roomId?: string;
  public?: boolean;
  /** @nullable */
  name?: string | null;
  type?: RenovationTypes;
}

export interface PostRenovationPermissions {
  renovationId?: string;
  /** @nullable */
  userId: string | null;
  canEdit?: boolean;
}

export interface PostRoom {
  width?: number;
  height?: number;
  length?: number;
  videoUploaded?: boolean;
  modelGenerated?: boolean;
  visibility?: boolean;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  thumbnail?: string | null;
}

export interface PostRoomInRenovation {
  roomId?: string;
  renovationId?: string;
  x?: number;
  y?: number;
  z?: number;
  rotationX?: number;
  rotationY?: number;
  rotationZ?: number;
  scaleX?: number;
  scaleY?: number;
  scaleZ?: number;
  visible?: boolean;
}

export interface PostRoomPermissions {
  roomId?: string;
  /** @nullable */
  userId?: string | null;
  renovationOnly?: boolean;
  canEdit?: boolean;
}

export interface PostShare {
  /** @nullable */
  userEmail: string | null;
  id?: string;
  canEdit?: boolean;
}

export interface Renovation {
  renovationId?: string;
  /** @nullable */
  ownerId: string | null;
  public?: boolean;
  /** @nullable */
  name?: string | null;
  modificationDate?: string;
  creationDate?: string;
  type?: RenovationTypes;
}

export interface RenovationApiGetReturnType {
  totalCount?: number;
  totalPages?: number;
  currentPage?: number;
  pageSize?: number;
  /** @nullable */
  returnedObjects?: Renovation[] | null;
}

export interface RenovationPerms {
  renovationId?: string;
  /** @nullable */
  userId?: string | null;
  canEdit?: boolean;
}

export interface RenovationPermsApiGetReturnType {
  totalCount?: number;
  totalPages?: number;
  currentPage?: number;
  pageSize?: number;
  /** @nullable */
  returnedObjects?: RenovationPerms[] | null;
}

export type RenovationTypes = typeof RenovationTypes[keyof typeof RenovationTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RenovationTypes = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;

export interface Room {
  roomId?: string;
  /** @nullable */
  ownerId?: string | null;
  width?: number;
  height?: number;
  length?: number;
  videoUploaded?: boolean;
  modelGenerated?: boolean;
  visibility?: boolean;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  thumbnail?: string | null;
  /** @nullable */
  generationDate?: string | null;
  creationDate?: string;
  /** @nullable */
  uploadDate?: string | null;
  modifyDate?: string;
  /** @nullable */
  error?: string | null;
}

export interface RoomApiGetReturnType {
  totalCount?: number;
  totalPages?: number;
  currentPage?: number;
  pageSize?: number;
  /** @nullable */
  returnedObjects?: Room[] | null;
}

export interface RoomInRenovation {
  id?: string;
  roomId?: string;
  renovationId?: string;
  x?: number;
  y?: number;
  z?: number;
  rotationX?: number;
  rotationY?: number;
  rotationZ?: number;
  scaleX?: number;
  scaleY?: number;
  scaleZ?: number;
  visible?: boolean;
}

export interface RoomInRenovationApiGetReturnType {
  totalCount?: number;
  totalPages?: number;
  currentPage?: number;
  pageSize?: number;
  /** @nullable */
  returnedObjects?: RoomInRenovation[] | null;
}

export interface RoomPerms {
  roomId?: string;
  /** @nullable */
  userId?: string | null;
  renovationOnly?: boolean;
  canEdit?: boolean;
}

export interface RoomPermsApiGetReturnType {
  totalCount?: number;
  totalPages?: number;
  currentPage?: number;
  pageSize?: number;
  /** @nullable */
  returnedObjects?: RoomPerms[] | null;
}

export interface SubscriptionInfo {
  renewalDate: string;
  /** @nullable */
  state: string | null;
}

export interface UserMetadata {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  surname?: string | null;
  /** @nullable */
  contactEmail?: string | null;
  /** @nullable */
  contactPhone?: string | null;
}

export interface UserMetadataDecorator {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  surname?: string | null;
  /** @nullable */
  contactEmail?: string | null;
  /** @nullable */
  contactPhone?: string | null;
  /** @nullable */
  region?: string | null;
  /** @nullable */
  description?: string | null;
}

export interface UserMetadataShop {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  surname?: string | null;
  /** @nullable */
  contactEmail?: string | null;
  /** @nullable */
  contactPhone?: string | null;
  /** @nullable */
  shopName?: string | null;
  /** @nullable */
  street?: string | null;
  /** @nullable */
  number?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  code?: string | null;
}

export type PostApiBlobStorageUploadObjectParams = {
id?: string;
};

export type PostApiBlobStorageUploadObjectBody = {
  file?: Blob;
};

export type PostApiBlobStorageUploadRoomParams = {
id?: string;
};

export type PostApiBlobStorageUploadRoomBody = {
  file?: Blob;
};

export type PutApiConfigParams = {
name?: string;
};

export type DeleteApiConfigParams = {
Name?: string;
};

export type PostApiModelsGenerateRoomParams = {
id?: string;
fileName?: string;
data_type?: string;
num_frames_target?: number;
max_num_iterations?: number;
};

export type PostApiModelsGenerateObjectParams = {
id?: string;
fileName?: string;
data_type?: string;
num_frames_target?: number;
max_num_iterations?: number;
};

export type GetAdminGetObjectsParams = {
nameFilter?: string;
objectIdFilter?: string;
videoUploadedFilter?: boolean;
modelGeneratedFilter?: boolean;
publicFilter?: boolean;
thumbnailFilter?: string;
widthFilter?: string;
heightFilter?: string;
lengthFilter?: string;
typeFilter?: ObjectTypes;
generationDateFilterUpper?: string;
generationDateFilterLower?: string;
creationDateFilterUpper?: string;
creationDateFilterLower?: string;
uploadDateFilterUpper?: string;
uploadDateFilterLower?: string;
modifyDateFilterUpper?: string;
modifyDateFilterLower?: string;
page?: number;
pageSize?: number;
orderBycol?: string;
orderByAsc?: boolean;
};

export type GetApiObjectAvailableParams = {
nameFilter?: string;
objectIdFilter?: string;
videoUploadedFilter?: boolean;
modelGeneratedFilter?: boolean;
publicFitler?: boolean;
thumbnailFilter?: string;
widthFilter?: string;
heightFilter?: string;
lengthFilter?: string;
typeFilter?: ObjectTypes;
generationDateFilterUpper?: string;
generationDateFilterLower?: string;
creationDateFilterUpper?: string;
creationDateFilterLower?: string;
uploadDateFilterUpper?: string;
uploadDateFilterLower?: string;
modifyDateFilterUpper?: string;
modifyDateFilterLower?: string;
page?: number;
pageSize?: number;
orderBycol?: string;
orderByAsc?: boolean;
};

export type PostApiObjectCreateAndGenerateParams = {
name?: string;
videoLength?: number;
type?: ObjectTypes;
};

export type PostApiObjectCreateAndGenerateBody = {
  file?: Blob;
};

export type PutApiObjectGsServiceModelGeneratedParams = {
id?: string;
secKey?: string;
value?: boolean;
};

export type PutApiObjectGsServiceErrorParams = {
id?: string;
secKey?: string;
error?: string;
};

export type GetApiObjectGsServiceErrorParams = {
id?: string;
};

export type GetApiObjectShareGetOwnerInfoParams = {
objectId?: string;
};

export type GetApiObjectShareGetUsersParams = {
roomId?: string;
};

export type GetApiObjectPermsParams = {
page?: number;
pageSize?: number;
orderBycol?: string;
orderByAsc?: boolean;
objectIdFilter?: string;
userIdFilter?: string;
renovationOnlyFilter?: boolean;
canEditFilter?: boolean;
};

export type PutApiObjectPermsParams = {
objectId?: string;
userId?: string;
};

export type GetAdminGetObjectsPermissionsParams = {
page?: number;
pageSize?: number;
orderByCol?: string;
orderByAsc?: boolean;
objectIdFilter?: string;
userIdFilter?: string;
renovationOnlyFilter?: boolean;
canEditFilter?: boolean;
};

export type DeleteApiObjectPermsObjectIdUserIdParams = {
objectId?: string;
userId?: string;
};

export type GetAdminGetObjectsInRenovationsParams = {
page?: number;
pageSize?: number;
filter?: string;
filterByCol?: string;
orderByCol?: string;
orderByAsc?: boolean;
idFilter?: string;
objectIdFilter?: string;
renovationIdFilter?: string;
xFilter?: string;
yFilter?: string;
zFilter?: string;
rotationXFilter?: string;
rotationYFilter?: string;
rotationZFilter?: string;
scaleXFilter?: string;
scaleYFilter?: string;
scaleZFilter?: string;
visibleFilter?: boolean;
};

export type GetApiObjectsInRenovationsAvailableParams = {
page?: number;
pageSize?: number;
filter?: string;
filterByCol?: string;
orderByCol?: string;
orderByAsc?: boolean;
idFilter?: string;
objectIdFilter?: string;
renovationIdFilter?: string;
xFilter?: string;
yFilter?: string;
zFilter?: string;
rotationXFilter?: string;
rotationYFilter?: string;
rotationZFilter?: string;
scaleXFilter?: string;
scaleYFilter?: string;
scaleZFilter?: string;
visibleFilter?: boolean;
};

export type PutApiObjectsInRenovationsParams = {
objectInRenovationId?: string;
};

export type GetApiPortalRenovationParams = {
idFilter?: string;
nameFilter?: string;
authorFilter?: string;
typeFilter?: PortalTypes;
modifyDateFilterUpper?: string;
modifyDateFilterLower?: string;
creationDateFilterUpper?: string;
creationDateFilterLower?: string;
page?: number;
pageSize?: number;
orderBycol?: string;
orderByAsc?: boolean;
ownerFilter?: string;
};

export type GetApiPortalObjectParams = {
idFilter?: string;
nameFilter?: string;
authorFilter?: string;
typeFilter?: PortalTypes;
modifyDateFilterUpper?: string;
modifyDateFilterLower?: string;
creationDateFilterUpper?: string;
creationDateFilterLower?: string;
page?: number;
pageSize?: number;
orderBycol?: string;
orderByAsc?: boolean;
ownerFilter?: string;
};

export type GetApiPortalThumbnailIdParams = {
type?: PortalTypes;
};

export type GetApiPortalObjectsInRenovationsParams = {
page?: number;
pageSize?: number;
orderByCol?: string;
orderByAsc?: boolean;
idFilter?: string;
objectIdFilter?: string;
renovationIdFilter?: string;
xFilter?: string;
yFilter?: string;
zFilter?: string;
rotationXFilter?: string;
rotationYFilter?: string;
rotationZFilter?: string;
scaleXFilter?: string;
scaleYFilter?: string;
scaleZFilter?: string;
visibleFilter?: boolean;
};

export type GetApiPortalRoomsInRenovationsParams = {
page?: number;
pageSize?: number;
orderByCol?: string;
orderByAsc?: boolean;
idFilter?: string;
roomIdFilter?: string;
renovationIdFilter?: string;
xFilter?: string;
yFilter?: string;
zFilter?: string;
rotationXFilter?: string;
rotationYFilter?: string;
rotationZFilter?: string;
scaleXFilter?: string;
scaleYFilter?: string;
scaleZFilter?: string;
visibleFilter?: boolean;
};

export type GetAdminGetRenovationsParams = {
nameFilter?: string;
renovationIdFilter?: string;
publicFilter?: boolean;
typeFilter?: RenovationTypes;
modificationDateFilterUpper?: string;
modificationDateFilterLower?: string;
creationDateFilterUpper?: string;
creationDateFilterLower?: string;
page?: number;
pageSize?: number;
orderBycol?: string;
orderByAsc?: boolean;
};

export type GetApiRenovationAvailableParams = {
nameFilter?: string;
renovationIdFilter?: string;
publicFilter?: boolean;
roomIdFilter?: string;
typeFilter?: RenovationTypes;
modificationDateFilterUpper?: string;
modificationDateFilterLower?: string;
creationDateFilterUpper?: string;
creationDateFilterLower?: string;
page?: number;
pageSize?: number;
orderBycol?: string;
orderByAsc?: boolean;
};

export type GetApiRenovationRoomIdParams = {
nameFilter?: string;
renovationIdFilter?: string;
publicFilter?: boolean;
typeFilter?: RenovationTypes;
modificationDateFilterUpper?: string;
modificationDateFilterLower?: string;
creationDateFilterUpper?: string;
creationDateFilterLower?: string;
page?: number;
pageSize?: number;
orderBycol?: string;
orderByAsc?: boolean;
};

export type GetApiRenovationShareGetOwnerInfoParams = {
renovationId?: string;
};

export type GetApiRenovationShareGetUsersParams = {
renovationId?: string;
};

export type GetAdminGetRenovationPermissionsParams = {
page?: number;
pageSize?: number;
filter?: string;
filterByCol?: string;
orderByCol?: string;
orderByAsc?: boolean;
renovationIdFilter?: string;
userIdFilter?: string;
canEditFilter?: boolean;
};

export type GetApiRenovationPermissionsParams = {
page?: number;
pageSize?: number;
orderBycol?: string;
orderByAsc?: boolean;
renovationIdFilter?: string;
userIdFilter?: string;
canViewFilter?: boolean;
canEditFilter?: boolean;
};

export type PutApiRenovationPermissionsParams = {
renovationId?: string;
userId?: string;
};

export type DeleteApiRenovationPermissionsRenovationIdUserIdParams = {
renovationId?: string;
userId?: string;
};

export type GetAdminGetRoomsParams = {
nameFilter?: string;
roomIdFilter?: string;
ownerIdFilter?: string;
videoUploadedFilter?: boolean;
modelGeneratedFilter?: boolean;
thumbnailFilter?: string;
widthFilter?: string;
heightFilter?: string;
lengthFilter?: string;
generationDateFilterUpper?: string;
generationDateFilterLower?: string;
creationDateFilterUpper?: string;
creationDateFilterLower?: string;
uploadDateFilterUpper?: string;
uploadDateFilterLower?: string;
modifyDateFilterUpper?: string;
modifyDateFilterLower?: string;
page?: number;
pageSize?: number;
orderBycol?: string;
orderByAsc?: boolean;
};

export type GetAdminGetRoomModelAdminParams = {
id?: string;
};

export type GetApiRoomAvailableParams = {
nameFilter?: string;
roomIdFilter?: string;
ownerIdFilter?: string;
videoUploadedFilter?: boolean;
modelGeneratedFilter?: boolean;
thumbnailFilter?: string;
widthFilter?: string;
heightFilter?: string;
lengthFilter?: string;
generationDateFilterUpper?: string;
generationDateFilterLower?: string;
creationDateFilterUpper?: string;
creationDateFilterLower?: string;
uploadDateFilterUpper?: string;
uploadDateFilterLower?: string;
modifyDateFilterUpper?: string;
modifyDateFilterLower?: string;
page?: number;
pageSize?: number;
orderBycol?: string;
orderByAsc?: boolean;
};

export type GetApiRoomOwnerIdParams = {
page?: number;
pageSize?: number;
filter?: string;
orderBycol?: string;
orderByAsc?: boolean;
};

export type PostApiRoomCreateAndGenerateParams = {
name?: string;
videoLength?: number;
};

export type PostApiRoomCreateAndGenerateBody = {
  file?: Blob;
};

export type PutApiRoomGsServiceModelGeneratedParams = {
id?: string;
secKey?: string;
value?: boolean;
};

export type PutApiRoomGsServiceErrorParams = {
id?: string;
secKey?: string;
error?: string;
};

export type GetApiRoomGsServiceErrorParams = {
id?: string;
};

export type GetApiRoomShareGetOwnerInfoParams = {
roomId?: string;
};

export type GetApiRoomShareGetUsersParams = {
roomId?: string;
};

export type GetAdminGetRoomPermissionsParams = {
page?: number;
pageSize?: number;
orderByCol?: string;
orderByAsc?: boolean;
roomIdFilter?: string;
userIdFilter?: string;
renovationOnlyFilter?: boolean;
canEditFilter?: boolean;
};

export type GetApiRoomPermissionsParams = {
page?: number;
pageSize?: number;
orderBycol?: string;
orderByAsc?: boolean;
roomIdFilter?: string;
userIdFilter?: string;
renovationOnlyFilter?: boolean;
canEditFilter?: boolean;
};

export type PutApiRoomPermissionsParams = {
roomId?: string;
userId?: string;
};

export type DeleteApiRoomPermissionsRoomIdUserIdParams = {
roomId?: string;
userId?: string;
};

export type GetAdminGetRoomsInRenovationsParams = {
page?: number;
pageSize?: number;
filter?: string;
filterByCol?: string;
orderByCol?: string;
orderByAsc?: boolean;
idFilter?: string;
roomIdFilter?: string;
renovationIdFilter?: string;
xFilter?: string;
yFilter?: string;
zFilter?: string;
rotationXFilter?: string;
rotationYFilter?: string;
rotationZFilter?: string;
scaleXFilter?: string;
scaleYFilter?: string;
scaleZFilter?: string;
visibleFilter?: boolean;
};

export type GetApiRoomsInRenovationsAvailableParams = {
page?: number;
pageSize?: number;
filter?: string;
filterByCol?: string;
orderByCol?: string;
orderByAsc?: boolean;
idFilter?: string;
roomIdFilter?: string;
renovationIdFilter?: string;
xFilter?: string;
yFilter?: string;
zFilter?: string;
rotationXFilter?: string;
rotationYFilter?: string;
rotationZFilter?: string;
scaleXFilter?: string;
scaleYFilter?: string;
scaleZFilter?: string;
visibleFilter?: boolean;
};

export type PutApiRoomsInRenovationsParams = {
roomInRenovationId?: string;
};

export type PatchApiUsersUpdateMetadataClearParams = {
metadataType?: string;
};

export type GetUserHasRoleParams = {
role?: string;
};

export type PatchApiUsersPasswordResetParams = {
email?: string;
};

